---
name: Bump Steampipe version

scms:
  github:
    kind: github
    spec:
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      email: '{{ requiredEnv "GITHUB_ACTOR" }}@users.noreply.github.com'
      owner: devops-ia
      repository: steampipe
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: main
      commitmessage:
        title: 'chore: bump steampipe to {{ source "steampipe" }}'

sources:
  steampipe:
    kind: githubRelease
    spec:
      owner: turbot
      repository: steampipe
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      versionFilter:
        kind: semver
        pattern: ">=2.0.0"

targets:
  dockerfile:
    name: "Update Steampipe version in Dockerfile"
    kind: file
    scmid: github
    sourceid: steampipe
    spec:
      file: Dockerfile
      matchpattern: 'ARG STEAMPIPE_VERSION=.*'
      replacepattern: 'ARG STEAMPIPE_VERSION={{ source "steampipe" }}'

actions:
  pr:
    kind: github/pullrequest
    scmid: github
    title: 'chore: bump steampipe to {{ source "steampipe" }}'
    spec:
      labels:
        - dependencies
